# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HDGLMC <- function(X1, r1, nperm) {
    .Call('GLMaSPU_HDGLMC', PACKAGE = 'GLMaSPU', X1, r1, nperm)
}

calcT0C <- function(tXUs, yresid, powV, nperm) {
    .Call('GLMaSPU_calcT0C', PACKAGE = 'GLMaSPU', tXUs, yresid, powV, nperm)
}

GeomanC <- function(X1, r1, nperm) {
    .Call('GLMaSPU_GeomanC', PACKAGE = 'GLMaSPU', X1, r1, nperm)
}

